function(include_external EXTERNAL_TARGETS_REF EXTERNAL_DIR EXTERNAL_INCLUDE_DIR EXTERNAL_BINARY_DIR EXTERNAL)
	set(external_dir ${EXTERNAL_DIR}/${EXTERNAL})
	if(IS_DIRECTORY ${external_dir})
		set(external_include_script "${EXTERNAL_INCLUDE_DIR}/${EXTERNAL}-include.cmake")
		if(EXISTS ${external_include_script})
			message("--> ${external_include_script}")
			include(${external_include_script})
		elseif(EXISTS ${external_dir}/CMakeLists.txt)
			message("--> ${external_dir}")
			add_subdirectory(${external_dir} ${EXTERNAL_BINARY_DIR}/${EXTERNAL} EXCLUDE_FROM_ALL)
			if (TARGET ${EXTERNAL})
				list(APPEND EXTERNAL_TARGETS ${EXTERNAL})
			endif()
		endif()
	endif()
	set_target_properties(${EXTERNAL_TARGETS} PROPERTIES FOLDER ${EXTERNALS_FOLDER})
	set(${EXTERNAL_TARGETS_REF} ${EXTERNAL_TARGETS} PARENT_SCOPE)
endfunction()

function(add_externals EXTERNAL_TARGETS_REF EXTERNAL_DIR EXTERNAL_INCLUDE_DIR EXTERNALS_FOLDER)
	get_filename_component(abs_external_dir ${EXTERNAL_DIR} ABSOLUTE)
	get_filename_component(abs_external_include_dir ${EXTERNAL_INCLUDE_DIR} ABSOLUTE)
	message("-- Collecting externals: ${abs_external_dir}")
	file(GLOB externals RELATIVE ${abs_external_dir} ${abs_external_dir}/*)
    foreach(external ${externals})
		include_external(EXTERNAL_TARGETS ${abs_external_dir} ${abs_external_include_dir} ${EXTERNAL_INCLUDE_DIR} ${external})
    endforeach()
	message("")
	set(${EXTERNAL_TARGETS_REF} ${EXTERNAL_TARGETS} PARENT_SCOPE)
endfunction()