function(include_external EXTERNAL_TARGETS EXTERNAL_DIR EXTERNAL)
	set(external_dir ${EXTERNAL_DIR}/${EXTERNAL})
    if(IS_DIRECTORY ${external_dir})
		set(external_include_script ${EXTERNAL_DIR}/cmake/${EXTERNAL}-include.txt)
		if(EXISTS ${external_include_script})
			message("--> ${external_include_script}")
			include(${external_include_script})
		elseif(EXISTS ${external_dir}/CMakeList.txt)
			message("--> ${external_dir}")
			add_subdirectory(${external_dir} EXCLUDE_FROM_ALL)
			if (TARGET ${EXTERNAL})
				list(APPEND ${EXTERNAL_TARGETS} ${EXTERNAL})
			endif()
		endif()
	endif()
	set_target_properties(${${EXTERNAL_TARGETS}} PROPERTIES FOLDER ${EXTERNALS_FOLDER})
	set(${EXTERNAL_TARGETS} ${${EXTERNAL_TARGETS}} PARENT_SCOPE)
endfunction()

function(add_externals EXTERNAL_TARGETS EXTERNAL_DIR EXTERNALS_FOLDER)
	set(external_dir ${CMAKE_CURRENT_LIST_DIR}/${EXTERNAL_DIR})
	message("-- Collecting externals")
	file(GLOB externals RELATIVE ${external_dir} ${external_dir}/*)
    foreach(external ${externals})
		include_external(${EXTERNAL_TARGETS} ${external_dir} ${external})
    endforeach()
	message("")
	set(${EXTERNAL_TARGETS} ${${EXTERNAL_TARGETS}} PARENT_SCOPE)
endfunction()